autofetch_sources: True
dotenv: .env
dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.5.1
  - OpenZeppelin/openzeppelin-contracts@4.8.0
  - ProjectOpenSea/seaport@1.5
compiler:
  solc:
    version: 0.8.17
    remappings:
      - '@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0'
      - 'seaport=ProjectOpenSea/seaport@1.5'
      
project_structure:
    build: build
    contracts: contracts
    interfaces: interfaces
    reports: reports
    scripts: scripts
    tests: tests

wallets:
  test_key: ${TEST_KEY}
  test_seller: ${TEST_SELLER}
  real_key: ${REAL_KEY}
  seller_key: ${SELLER_KEY}
  
networks:
  default: development
  polygon-main-alchemy:
    priority_fee: auto
    required_confirmations: 3
    matic_usd_oracle: '0xAB594600376Ec9fD91F8e885dADF0CE036862dE0'
    eth_token: '0x7ceb23fd6bc0add59e62ac25578270cff1b9f619'
    eth_usd_oracle: '0xF9680D99D6C9589e2a93a78A04A279e509205945'
    usdc_token: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174'
    usdc_usd_oracle: '0x0000000000000000000000000000000000000000'
    testnet: false
    verify: true
    local: false
    forked: false
  polygon-test-alchemy:
    priority_fee: auto
    required_confirmations: 3
    matic_usd_oracle: '0xd0D5e3DB44DE05E9F294BB0a3bEEaF030DE24Ada'
    eth_token: '0xA6FA4fB5f76172d178d61B04b0ecd319C5d1C0aa'
    eth_usd_oracle: '0x0715A7794a1dc8e42615F059dD6e406A6594651A'
    usdc_token: '0x0FA8781a83E46826621b3BC094Ea2A0212e71B23'
    usdc_usd_oracle: '0x0000000000000000000000000000000000000000'
    testnet: true
    verify: true
    local: false
    forked: false
  development: 
    testnet: false
    verify: false
    local: true
    forked: false